version: '3'
services:
  postgres-ccbc:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "ccbc"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ccbc"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"