# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: ccbc-support CI with Java & Gradle

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ccbc-support/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ccbc-support/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: run test
        run: ./gradlew -p ccbc-support test
      - name: Build with Gradle
        run: ./gradlew build -p ccbc-support -x test
