name: tagging-deployment
on:
  push:
    tags:
      - '[1-9].x'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-hotfix.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get the commit hash
        id: get_commit_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short=8 HEAD)"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Build Docker Image Tag with Git Tagging and Push to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          path: ./ccbc-worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          repository: ccbcdev/ccbc-worker
          tags: ${{ steps.get_version.outputs.version }}
      - name: Build Docker Image with Latest Tagging and Push to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          path: ./ccbc-worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          repository: ccbcdev/ccbc-worker
          tags: latest